
const mongoose = require('mongoose');

const propertySchema = new mongoose.Schema({
  userId: { type: String, required: true },
  userName: { type: String, required: true },
  propertyType: { type: String, default: '' },
  negotiable: { type: String, default: '' },
  price: { type: String, default: '' },
  ownership: { type: String, default: '' },
  propertyAge: { type: String, default: '' },
  propertyApproved: { type: String, default: '' },
  propertyDescription: { type: String, default: '' },
  bankLoan: { type: String, default: '' },
  length: { type: String, default: '' },
  breadth: { type: String, default: '' },
  totalArea: { type: String, default: '' },
  areaUnit: { type: String, default: '' },
  bhk: { type: String, default: '' },
  floor: { type: String, default: '' },
  attached: { type: String, default: '' },
  westernToilet: { type: String, default: '' },
  furnished: { type: String, default: '' },
  carParking: { type: String, default: '' },
  lift: { type: String, default: '' },
  electricity: { type: String, default: '' },
  facing: { type: String, default: '' },
  nameType: { type: String, default: '' },
  mobile: { type: String, default: '' },
  postedBy: { type: String, default: '' },
  saleType: { type: String, default: '' },
  featuredPackage: { type: String, default: '' },
  ppdPackage: { type: String, default: '' },
  email: { type: String, required: true },
  city: { type: String, default: '' },
  area: { type: String, default: '' },
  pincode: { type: String, default: '' },
  address: { type: String, default: '' },
  landmark: { type: String, default: '' },
  latitude: { type: String, default: '' },
  longitude: { type: String, default: '' },
}, { timestamps: true });

module.exports = mongoose.model('Property', propertySchema);